version: "3"
services:
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/deployments/frontend/index.html
    depends_on:
      - Docker-Test-App
  redis-server:
    image: "redis:3"
    restart: always
    #command: ["redis-server", "--bind", "0.0.0.0"]

  mongo:
    image: mongo:4.4.12
    restart: always
    volumes:
      - mongodb:/data/db
   
  Docker-Test-App:
    image: armaghan0006/docker-test-app:1.0.3
    # build: .
    restart: always
    depends_on:
      - mongo
      - redis-server
    environment:
      - mongoCon=mongodb://mongo:27017/nodejs-redis
      - REDIS_HOST=redis-server
      - JWT_KEY=SecretjwtKey
      - PORT=3000
    
networks:
  internal-network:

volumes:
 mongodb: